#lang sicp
(define (make-mobile left right)
  (list left right))
(define (make-branch length structure)
  (list length structure))
;2-29 a)
(define (left-branch mobile)
  (car mobile))
(define (right-branch mobile)
  (car(cdr mobile)))
(define (branch-length branch)
  (car branch))
(define (branch-structure branch)
  (car(cdr branch)))
;2-29 b)
(define (mobile? x)
  (and (pair? x)
     (pair? (left-branch x))
     (pair? (right-branch x))))
(define (branch? x)
  (and (pair? x)
       (number? (branch-length x))))
(define (total-weight x)
  (cond ((null? x) 0)
    ((mobile? x)(+ (total-weight (left-branch x))(total-weight (right-branch x))))
    ((and (branch? x) (mobile?(branch-structure x))) (total-weight (branch-structure x)))
    ((and (branch? x )(not (mobile?(branch-structure x)))) (branch-structure x))))
(define branch-1 (make-branch 3 2))
(define branch-2 (make-branch 2 3))
(define mobile-1 (make-mobile branch-1 branch-2))
(define branch-3 (make-branch 2 mobile-1))
(define mobile-2 (make-mobile branch-3 branch-2))
(total-weight mobile-2)
;2-29 c)
(define (balanced? x)
  (if (mobile? x)
      (let((left-structure (branch-structure(left-branch x)))
	   (right-structure (branch-structure(right-branch x)))
	   (left-length (branch-length (left-branch x)))
	   (right-length (branch-length (right-branch x))))
	(if (= (* left-length (total-weight (left-branch x)))(* right-length (total-weight (right-branch x))))
            (cond ((and (mobile? left-structure)(mobile? right-structure )) (and (balanced? left-structure)(balanced? right-structure)))
	      ((and (not(mobile? left-structure))(mobile? right-structure )) (balanced? right-structure))
	      ((and (mobile? left-structure )(not(mobile? right-structure))) (balanced? left-structure))
	      (else #t))
	    #f))
      (error "要输入一个双叉体")))
(balanced? mobile-1)
;2-30 d)
;仅仅需要改2-29 a)中的四个函数
