#lang sicp
(define (make-point x y)(cons x y))
(define x-point car)
(define y-point cdr)
(define (mid-point x y) (cons (/ (+ (x-point x) (x-point y)) 2.0)
                              (/ (+ (y-point x) (y-point y)) 2.0)))
(define (print-point p)
        (newline)
        (display "(")
        (display (x-point p))
        (display ",")
        (display (y-point p))
        (display ")"))
(define (make-segment x y) (cons x y))
(define start-segment car)
(define end-segment cdr)
;引入开方
(define tolerance 0.00001)
(define (fixed-point f first-guess)
        (define (close-enough? v1 v2)
                (< (abs (- v1 v2))tolerance))
        (define (try guess)
                (let ((next (f guess)))
                     (if(close-enough? guess next)
                                next
                                (try next))))
        (try first-guess))
(define (sqrt x)
        (fixed-point (lambda (y) (/ (+ y (/ x y)) 2.0) ) 1.0))
;两点之间的距离
(define (distance x y)
        (sqrt (+(*(- (x-point x)(x-point y))(- (x-point x)(x-point y)))
                (*(- (y-point x)(y-point y))(- (y-point x)(y-point y))))))
;第一种定义的方式
(define (rectangle-point p1 p2 p3 p4) (cons (cons p1 p2) (cons p4 p3)))
;第二种定义的方式
(define (rectangle-segment s1 s2)(cons s1 s2))
(define (perimeter p)
        (*(+(distance (car (car p)) (car (cdr p)))
            (distance (car (cdr p)) (cdr (cdr p)))) 
          2))
(perimeter (rectangle-point (cons 0 0) (cons 1 0) (cons 1 1) (cons 0 1)))