#lang sicp
(define (map proc items)
  (if (null? items)
      nil
      (cons (proc (car items))
	    (map proc (cdr items)))))
(define (square-list lst)
  (cond ((null? lst) nil)
    ((number? lst)(* lst lst))
    (else (cons (square-list (car lst))
	   (square-list (cdr lst))))))
(define a  (list 1 (list 2 3) 4))
(square-list a)
(define (square-list0 lst)
  (map (lambda (sub)
	 (cond ((null? sub) nil)
              ((pair? sub) (square-list0 sub))
               (else (* sub sub))))  
       lst))
(square-list0 a)
(define t1 (list 1 (list 2 3) 4))
(square-list t1)    ;预期 (1 (4 9) 16)
(square-list0 t1)   ;预期 (1 (4 9) 16)
(define t2 (list (list 1 2) 3 (list 4 (list 5 6))))
(square-list t2)   ;预期 ((1 4) 9 (16 (25 36)))
(square-list0 t2)  ;预期 ((1 4) 9 (16 (25 36)))
(define t3 '())
(square-list t3)   ;预期 ()
(square-list0 t3)  ;预期 ()
(define t4 (list 2 5 7))
(square-list t4)   ;预期 (4 25 49)
(square-list0 t4)  ;预期 (4 25 49)
(define t5 (list 1 '() (list 8)))
(square-list t5)   ;预期 (1 () (64))
(square-list0 t5)  ;预期 (1 () (64))
(square-list 9)    ;预期 81
;; (square-list0 9) ; ❌报错！map需要列表参数，这是契约差异
(define t8 (list (list (list 3))))
(square-list t8)   ;预期 (((9)))
(square-list0 t8)  ;预期 (((9)))
