#lang sicp
(define (Pascal-triangle x y)
        (cond ((= x y) 1)
              ((= y 1) 1)
              (else (+ (Pascal-triangle (- x 1) y)
                       (Pascal-triangle (- x 1) (- y 1))))))
(display(Pascal-triangle 1 1))
(newline)
(display(Pascal-triangle 2 1))
(display(Pascal-triangle 2 2))
(newline)
(display(Pascal-triangle 3 1))
(display(Pascal-triangle 3 2))
(display(Pascal-triangle 3 3))
(newline)
(display(Pascal-triangle 4 1))
(display(Pascal-triangle 4 2))
(display(Pascal-triangle 4 3))
(display(Pascal-triangle 4 4))