#lang sicp

(define (smallest-divisor n)
  (find-divisor-iter n 2))
(define (find-divisor-iter n tmp)
  (cond ((> (* tmp tmp) n) n)
        ((= (remainder n tmp) 0) tmp)
        (else (find-divisor-iter n (+ tmp 1)))))
(define (prime? n)
  (= n (smallest-divisor n)))

(define (report-prime elapsed-time)
        (display"***")
        (display elapsed-time))
(define (start-prime-test n start-time)
        (if (prime? n)
            (report-prime (- (runtime) start-time))))
(define (timed-prime-test n)
        (newline)
        (display n)
        (start-prime-test n (runtime)))

(define (search-for-prime n count)
        (cond ((= count 3) (display "end"))
              ((= (remainder n 2) 0)(search-for-prime (+ n 1)count))
              ((prime? n) (begin (timed-prime-test n)
                                 (search-for-prime (+ n 1)(+ count 1))))
              (else (search-for-prime (+ n 1)count)))) 
(search-for-prime 1000 0)
(search-for-prime 10000 0)
(search-for-prime 1000000 0)