#lang sicp
(define (square x) (* x x))
(define (expmod base exp m)
        (cond ((= exp 0) 1)
              ((even? exp)
               (remainder(square (expmod base (/ exp 2) m))m))
              (else (remainder(* base(expmod base (- exp 1) m))m))))
(define (fermat-test n a)
        (= (expmod a n n) a))
(define (fast-prime? n times)
        (cond ((= times n) (display"yes"))
              ((fermat-test n times) (fast-prime? n (+ times 1)))
              (else "no")))

(fast-prime? 561 1)
(newline)
(fast-prime? 1105 1)
(newline)
(fast-prime? 1729 1)
(newline)
(fast-prime? 2465 1)
(newline)
(fast-prime? 2821 1)
(newline)
(fast-prime? 6601 1)
(newline)