#lang sicp
(define (square x) (* x x))
(define (expmod base exp m)
        (cond ((= exp 0) 1)
              ((even? exp)
               (remainder(square (expmod base (/ exp 2) m))m))
              (else (remainder(* base(expmod base (- exp 1) m))m))))
(define (fermat-test n)
        (define (try-it a)
                (= (expmod a (- n 1) n) 1))
        (try-it (+ 1 (random (- n 1)))))
(define (fast-prime? n times)
        (cond ((= times 0) 1)
              ((fermat-test n) (fast-prime? n (- times 1)))
              (else 0)))
(fast-prime? 561 100)
(newline)
(fast-prime? 1105 100)
(newline)
(fast-prime? 1729 100)
(newline)
(fast-prime? 2465 100)
(newline)
(fast-prime? 2821 100)
(newline)
(fast-prime? 6601 100)
(newline)
(fast-prime? 100003 100)