#lang sicp
(define (cont-frac-iter n d k count out)
        (define (f befor x y)
                (/ x (+ y befor)))
        (cond ((= count 0) out)
              (else (let ((N_i/N_d (/ (n count) (d count)))
                          (N_i (n count))
                          (D_i (d count)))   
                         (cond ((= count k) (cont-frac-iter n d k (- count 1) (* out N_i/N_d)))
                               (else  (cont-frac-iter n d k (- count 1) (f out N_i D_i))))))))
(/ 1.0(cont-frac-iter (lambda (i) 1.0) (lambda (i) 1.0) 1000 1000 1))

(define (cont-frac n d k count)
        (define (f befor x y)
                (/ x (+ y befor)))
        (let ((N_i/N_d (/ (n count) (d count)))
              (N_i (n count))
              (D_i (d count)))   
             (cond ((= count k) N_i/N_d)
                   (else (f (cont-frac n d k (+ 1 count)) N_i D_i)))))
(/ 1.0(cont-frac (lambda (i) 1.0) (lambda (i) 1.0) 1000 0))
