#lang sicp
(define (fast-expt-iter n b a)
        (cond ((= n 0) a)
              ((= (remainder n 2) 0) (fast-expt-iter (/ n 2) (* b b) a))
              (else (fast-expt-iter (- n 1) b (* a b)))))
(define (fast-expt n b)(fast-expt-iter n b 1))
(define (cont-frac-iter n d k count out)
        (define (f befor x y)
                (/ x (- y befor)))
        (cond ((= count 0) out)
              (else (let ((N_i/N_d (/ (n count) (d count)))
                          (N_i (n count))
                          (D_i (d count)))   
                         (cond ((= count k) (cont-frac-iter n d k (- count 1) (* out N_i/N_d)))
                               (else  (cont-frac-iter n d k (- count 1) (f out N_i D_i))))))))
(define (tan-cf x k)
        (cont-frac-iter (lambda (i) (fast-expt i x)) (lambda (i) (- (* 2.0 i) 1)) k k 1))
(tan-cf -0.7853981 100000)
