#lang sicp
(define (find-divisor-iter n tmp)
        (cond( (< n (* tmp tmp)) (display "是素数"))
             ( (= (remainder n tmp)0) (display "不是素数"))
             (else (find-divisor-iter n (+ tmp 1)))))
(define (find-divisor n)(find-divisor-iter n 2))
(find-divisor 2)
(newline)
(find-divisor 3)
(newline)
(find-divisor 4)
(newline)
(find-divisor 5)
(newline)
(find-divisor 6)
(newline)
(find-divisor 7)
(newline)
(find-divisor 8)
(newline)
(find-divisor 9)
(newline)
