#lang sicp
(define (abs x)(if (> x 0) x (- 0 x)))
(define (close-enough? x y)(< (abs (- x y)) 0.0001))
(define (search f neg-point pos-point)
        (let ((midpoint (/ (+ neg-point pos-point) 2.0)))
             (if (close-enough? neg-point pos-point)
                 midpoint
                 (let ((test-value (f midpoint)))
                      (cond ((positive? test-value)
                             (search f neg-point midpoint))
                            ((negative? test-value)
                             (search f test-value pos-point))
                            (else midpoint))))))
(define (half-interval-method f a b)
        (let ((a-value (f a))
              (b-value (f b)))
             (cond ((and (negative? a-value) (positive? b-value)) 
                    (search f a b))
                   ((and (negative? b-value) (positive? a-value)) 
                    (search f b a))
                   (error "worry"))))
(half-interval-method (lambda (x) (- x 1)) 2 2)
